{% set name = "poetry-kernel" %}
{% set version = "0.1.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/poetry-kernel-{{ version }}.tar.gz
  sha256: a586631fca31185dbb5f4b8e88a8a30b00bf857b6bc5935b277cfe4f48e90f27

build:
  number: 2
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - colorama ~=0.4.4
    - jupyter_client >=7.0.1
    - python >={{ python_min }}

test:
  imports:
    - poetry_kernel
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/pathbird/poetry-kernel
  summary: Python Jupyter kernel using Poetry for dependency management
  license: MIT
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - thewchan
