{% set name = "poetry-kernel" %}
{% set version = "0.1.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/poetry-kernel-{{ version }}.tar.gz
  sha256: 2e0ed6a8d521efa50ae913d9f5dfc0bb08fa27b466c9d31f8bb63c852d8d86e4

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - colorama ~=0.4.4
    - jupyter_client ~=7.0.1
    - python >=3.7

test:
  imports:
    - poetry_kernel
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pathbird/poetry-kernel
  summary: Python Jupyter kernel using Poetry for dependency management
  license: MIT
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - thewchan
